# Generated by Django 5.2.8 on 2025-12-02 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_financeiro', '0002_job_alter_client_email_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='app_financeiro.client', verbose_name='Cliente'),
        ),
    ]
