# Generated by Django 5.2.8 on 2025-12-02 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_financeiro', '0004_alter_client_email_alter_client_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Número')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('issue_date', models.DateField(verbose_name='Data de emissão')),
                ('due_date', models.DateField(verbose_name='Data de vencimento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('vencida', 'Vencida'), ('paga', 'Paga')], default='pendente', max_length=10, verbose_name='Status')),
                ('last_reminder', models.DateField(blank=True, null=True, verbose_name='Último lembrete')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to='app_financeiro.client', verbose_name='Cliente')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrancas', to='app_financeiro.job', verbose_name='Job (opcional)')),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
                'ordering': ['-issue_date', '-id'],
            },
        ),
    ]
