# Generated by Django 5.2.8 on 2025-12-03 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_financeiro', '0005_cobranca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Amazônia Engenharia', max_length=255, verbose_name='Razão Social')),
                ('company_cnpj', models.CharField(default='12.345.678/0001-90', max_length=20, verbose_name='CNPJ')),
                ('company_email', models.EmailField(default='admin@amazoniaengenharia.com', max_length=254, verbose_name='Email')),
                ('company_phone', models.CharField(default='(92) 99999-9999', max_length=20, verbose_name='Telefone')),
                ('company_address', models.TextField(default='Rua das Palmeiras, 123 - Manaus, AM', verbose_name='Endereço')),
                ('whatsapp_enabled', models.BooleanField(default=False, verbose_name='WhatsApp ativo')),
                ('evolution_api_url', models.CharField(blank=True, max_length=255, verbose_name='URL Evolution API')),
                ('evolution_api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key')),
                ('evolution_instance_name', models.CharField(blank=True, max_length=100, verbose_name='Nome da Instância')),
                ('evolution_sandbox', models.BooleanField(default=True, verbose_name='Modo Sandbox')),
                ('reminder_days_before', models.PositiveIntegerField(default=3, verbose_name='Dias antes do vencimento')),
                ('reminder_days_after', models.PositiveIntegerField(default=5, verbose_name='Dias após vencimento')),
                ('reminder_on_due_date', models.BooleanField(default=True, verbose_name='Enviar no vencimento')),
                ('reminder_include_weekends', models.BooleanField(default=False, verbose_name='Incluir finais de semana')),
                ('reminder_business_hours_only', models.BooleanField(default=True, verbose_name='Apenas horário comercial')),
                ('template_before', models.TextField(default='Olá {nome}! 🌿\nLembrete amigável: sua fatura no valor de {valor} vence em {dias_restantes} dia(s) ({vencimento}).\n\nPara evitar transtornos, realize o pagamento até a data de vencimento.\n\n*Amazônia Engenharia*', verbose_name='Template antes do vencimento')),
                ('template_due', models.TextField(default='Olá {nome}! 📅\nSua fatura no valor de {valor} vence hoje ({vencimento}).\n\nPor favor, realize o pagamento para manter seus serviços em dia.\n\n*Amazônia Engenharia*', verbose_name='Template no vencimento')),
                ('template_after', models.TextField(default='Olá {nome}! ⚠️\nSua fatura no valor de {valor} está vencida desde {vencimento}.\n\nEntre em contato conosco para regularizar a situação.\n\n*Amazônia Engenharia*', verbose_name='Template após vencimento')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cobranca_vencendo', 'Cobrança Vencendo'), ('cobranca_vencida', 'Cobrança Vencida'), ('job_proximo_entrega', 'Job Próximo da Entrega'), ('info', 'Informação'), ('success', 'Sucesso'), ('warning', 'Aviso'), ('error', 'Erro')], default='info', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
