# Generated by Django 5.2.8 on 2025-12-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_financeiro', '0006_systemconfig_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='job',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor'),
        ),
    ]
